stages:
  - build

build:
  stage: build
  timeout: 2.5 hours
  image:
    name: ${KANIKO_IMAGE}
    entrypoint: [""]
  tags:
    - cloud
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}"
  rules:
    - if: '$CI_COMMIT_TAG != null'
      when: always
